name       : r
version    : 3.2.4
release    : 4
source     :
    - http://cran.r-project.org/src/base/R-3/R-3.2.4-revised.tar.gz : d484844d519951b68e4462dd902cba1d25a27d89a7d8bcfb4652635f1c1ab43f
license    : GPL-2.0
summary    : R is a system for statistical computation and graphics.
description: |
    R is a system for statistical computation and graphics.
builddeps  :
    - pkgconfig(cairo-gl)
    - pkgconfig(icu-io)
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xmu)
    - pkgconfig(zlib)
    - gfortran
    - libiconv-devel
    - libjpeg-turbo-devel
    - readline-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
