name       : r
version    : 3.3.1
release    : 7
source     :
    - http://cran.r-project.org/src/base/R-3/R-3.3.1.tar.gz : 3dc59ae5831f5380f83c169bac2103ad052efe0ecec4ffa74bde4d85a0fda9e2
license    : GPL-2.0
component  : programming
summary    : R is a system for statistical computation and graphics.
description: |
    R is a system for statistical computation and graphics.
optimize   : speed
builddeps  :
    - pkgconfig(cairo-gl)
    - pkgconfig(icu-io)
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xmu)
    - pkgconfig(zlib)
    - gfortran
    - libiconv-devel
    - libjpeg-turbo-devel
    - readline-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
