name       : r
version    : 3.4.0
release    : 16
source     :
    - https://cran.r-project.org/src/base/R-3/R-3.4.0.tar.gz : 288e9ed42457c47720780433b3d5c3c20983048b789291cc6a7baa11f9428b91
license    : GPL-2.0
component  : programming
summary    : R is a system for statistical computation and graphics.
description: |
    R is a system for statistical computation and graphics.
optimize   : speed
patterns   :
    - /usr/include/R
    - /usr/lib64/pkgconfig
builddeps  :
    - pkgconfig(cairo-gl)
    - pkgconfig(icu-io)
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - pkgconfig(xmu)
    - pkgconfig(zlib)
    - gfortran
    - libiconv-devel
    - libjpeg-turbo-devel
    - openblas-devel
    - readline-devel
    - xdg-utils
setup      : |
    unset LD_AS_NEEDED
    %configure \
        --enable-R-shlib \
        --with-blas="-lopenblas" \
        rdocdir=/usr/share/doc/R \
        rincludedir=/usr/include/R \
        rsharedir=/usr/share/R
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    %make_install
check      : |
    %make check
