name       : r
version    : 4.0.4
release    : 37
source     :
    - https://cran.r-project.org/src/base/R-4/R-4.0.4.tar.gz : 523f27d69744a08c8f0bd5e1e6c3d89a4db29ed983388ba70963a3cd3a4a802e
license    : GPL-2.0-or-later
component  : programming
summary    : R is a system for statistical computation and graphics.
description: |
    R is a system for statistical computation and graphics.
optimize   : speed
patterns   :
    - /usr/include/R
    - /usr/lib64/pkgconfig
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(pangocairo)
    - pkgconfig(tk)
    - pkgconfig(xmu)
    - pkgconfig(xscrnsaver)
    - bzip2-devel
    - gfortran
    - libiconv-devel
    - openblas-devel
    - xdg-utils
environment: |
    unset LD_AS_NEEDED
setup      : |
    %configure \
        --enable-R-shlib \
        --with-blas="-lopenblas" \
        --with-tcltk \
        rdocdir=/usr/share/doc/R \
        rincludedir=/usr/include/R \
        rsharedir=/usr/share/R
build      : |
    %make
install    : |
    %make_install
