name       : r
version    : 3.5.1
release    : 26
source     :
    - https://cran.r-project.org/src/base/R-3/R-3.5.1.tar.gz : 0463bff5eea0f3d93fa071f79c18d0993878fd4f2e18ae6cf22c1639d11457ed
license    : GPL-2.0-or-later
component  : programming
summary    : R is a system for statistical computation and graphics.
description: |
    R is a system for statistical computation and graphics.
optimize   : speed
patterns   :
    - /usr/include/R
    - /usr/lib64/pkgconfig
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pangocairo)
    - pkgconfig(xmu)
    - bzip2-devel
    - gfortran
    - libiconv-devel
    - openblas-devel
    - xdg-utils
setup      : |
    unset LD_AS_NEEDED
    %configure \
        --enable-R-shlib \
        --with-blas="-lopenblas" \
        rdocdir=/usr/share/doc/R \
        rincludedir=/usr/include/R \
        rsharedir=/usr/share/R
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    %make_install
check      : |
    %make check
